-- Required files to be visible from anywhere
require ('game_settings')
require ('timers')
require ('commands')
require ('barebones')
require ("statcollection/init")
require ('game')
require ('game_round')
require ('duel_round')
require ('wave_spawner')
require ('player')
require ('unit')
require ('popups')
require ('notifications')
require ('damage')
require ('selection')
require ('wiki')
require ('precache')
require ('wave_unit')

-- Create the game mode when we activate
function Activate()
	GameRules.GameMode = GameMode()
	GameRules.GameMode:InitGameMode()
end
